In [57]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

In [44]:
data_source = "https://raw.githubusercontent.com/yantonglll/ECON570_Final_Project/main/ALL%20Prices%202019-2021%20mar.csv"
data = pd.read_csv(data_source)
data

,month,town,town_dummy,flat_type,block,street_name,address,latitude,longitude,storey_range,...,price_psm_yearly,Core CPI,price cpi_adj,price_psm cpi_adj,bala lease pct,price lease_adj implied,price_psm lease_adj implied,price cpi_lease_adj implied,price_psm cpi_lease_adj implied,year_gni
0,2019-01,ANG MO KIO,2,5 ROOM,700B,ANG MO KIO AVE 6,700B ANG MO KIO AVE 6 SINGAPORE,1.369457,103.846276,19 TO 21,...,86.160860,99.961,794109.7028,7154.141466,92.2,826516.268980,7446.092513,826838.736104,7448.997622,78847
1,2019-01,ANG MO KIO,2,5 ROOM,316A,ANG MO KIO ST 31,316A ANG MO KIO ST 31 SINGAPORE,1.364621,103.847080,19 TO 21,...,81.395349,99.961,770300.4172,7002.731065,93.3,792282.958199,7202.572347,792592.069145,7205.382446,78847
2,2019-01,ANG MO KIO,2,4 ROOM,310B,ANG MO KIO AVE 1,310B ANG MO KIO AVE 1 SINGAPORE,1.364778,103.844221,25 TO 27,...,84.918478,99.961,750292.6141,7815.548064,95.0,757894.736842,7894.736842,758190.431091,7897.816991,78847
3,2019-01,ANG MO KIO,2,5 ROOM,315B,ANG MO KIO ST 31,315B ANG MO KIO ST 31 SINGAPORE,1.364079,103.847476,13 TO 15,...,76.955603,99.961,728284.0308,6620.763916,93.3,749067.524116,6809.704765,749359.774457,6812.361586,78847
4,2019-01,ANG MO KIO,2,5 ROOM,353,ANG MO KIO ST 32,353 ANG MO KIO ST 32 SINGAPORE,1.364015,103.851622,16 TO 18,...,81.705948,99.961,728284.0308,6620.763916,91.4,764638.949672,6951.263179,764937.275239,6953.975229,78847
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52636,2021-03,YISHUN,5,3 ROOM,110,YISHUN RING RD,110 YISHUN RING RD SINGAPORE,1.433340,103.829168,07 TO 09,...,66.650391,100.400,271912.3506,4248.630478,82.4,318058.252427,4969.660194,316791.088078,4949.860751,75000
52637,2021-03,YISHUN,5,3 ROOM,712,YISHUN AVE 5,712 YISHUN AVE 5 SINGAPORE,1.430248,103.828862,01 TO 03,...,63.567362,100.400,266932.2709,3925.474573,81.2,316847.290640,4659.518980,315584.950818,4640.955160,75000
52638,2021-03,YISHUN,5,2 ROOM,424B,YISHUN AVE 11,424B YISHUN AVE 11 SINGAPORE,1.423215,103.848264,07 TO 09,...,59.482956,100.400,258964.1434,5509.875392,95.2,262184.873950,5578.401574,261140.312672,5556.176866,75000
52639,2021-03,YISHUN,5,2 ROOM,459,YISHUN AVE 11,459 YISHUN AVE 11 SINGAPORE,1.421059,103.846357,07 TO 09,...,57.234432,100.400,249003.9841,5187.583001,94.8,253164.556962,5274.261603,252155.933266,5253.248609,75000
52640,2021-03,YISHUN,5,2 ROOM,459,YISHUN AVE 11,459 YISHUN AVE 11 SINGAPORE,1.421059,103.846357,01 TO 03,...,48.076923,100.400,209163.3466,4357.569721,94.8,212658.227848,4430.379747,211810.983899,4412.728831,75000

In [6]:
dummies = pd.get_dummies(data['town_dummy'])

In [7]:
dummies.rename(columns={1:'d1',2:'d2',3:'d3',4:'d4',5:'d5',6:'d6'},inplace = True)

In [8]:
dataTown=pd.concat([data,dummies.reindex(data.index)],axis=1)

In [9]:
dataTown['Covid']=dataTown.month.between('2020-02','2021-03').astype(int)

In [10]:
dataTown['Covid1']=dataTown['d1']*dataTown['Covid']

In [11]:
dataTown['Covid2']=dataTown['d2']*dataTown['Covid']
dataTown['Covid3']=dataTown['d3']*dataTown['Covid']
dataTown['Covid4']=dataTown['d4']*dataTown['Covid']
dataTown['Covid5']=dataTown['d5']*dataTown['Covid']
dataTown['Covid6']=dataTown['d6']*dataTown['Covid']

In [12]:
dataTown['flat_type'].replace('ROOM','',regex=True,inplace=True)

In [36]:
dataTown.head()

,month,town,town_dummy,flat_type,block,street_name,address,latitude,longitude,storey_range,...,d4,d5,d6,Covid,Covid1,Covid2,Covid3,Covid4,Covid5,Covid6
0,2019-01,ANG MO KIO,2,5,700B,ANG MO KIO AVE 6,700B ANG MO KIO AVE 6 SINGAPORE,1.369457,103.846276,19 TO 21,...,0,0,0,0,0,0,0,0,0,0
1,2019-01,ANG MO KIO,2,5,316A,ANG MO KIO ST 31,316A ANG MO KIO ST 31 SINGAPORE,1.364621,103.847080,19 TO 21,...,0,0,0,0,0,0,0,0,0,0
2,2019-01,ANG MO KIO,2,4,310B,ANG MO KIO AVE 1,310B ANG MO KIO AVE 1 SINGAPORE,1.364778,103.844221,25 TO 27,...,0,0,0,0,0,0,0,0,0,0
3,2019-01,ANG MO KIO,2,5,315B,ANG MO KIO ST 31,315B ANG MO KIO ST 31 SINGAPORE,1.364079,103.847476,13 TO 15,...,0,0,0,0,0,0,0,0,0,0
4,2019-01,ANG MO KIO,2,5,353,ANG MO KIO ST 32,353 ANG MO KIO ST 32 SINGAPORE,1.364015,103.851622,16 TO 18,...,0,0,0,0,0,0,0,0,0,0

In [37]:
for col in dataTown.columns:
    print(col)

month
town
town_dummy
flat_type
block
street_name
address
latitude
longitude
storey_range
storey
area_sqm
flat_model
lease_start
lease_rem
resale_price
price_psm
price_psm_yearly
Core CPI
price cpi_adj
price_psm cpi_adj
bala lease pct
price lease_adj implied
price_psm lease_adj implied
price cpi_lease_adj implied
price_psm cpi_lease_adj implied
year_gni
d1
d2
d3
d4
d5
d6
Covid
Covid1
Covid2
Covid3
Covid4
Covid5
Covid6

In [60]:
dataTown['Y']=dataTown['price cpi_adj']

In [65]:
est1 = smf.ols(formula="Y ~ flat_type + storey + area_sqm + lease_rem + d1 + d2 + d3 + d4 + d5 + d6 + Covid + Covid1 + Covid2 + Covid3 + Covid4 + Covid5 + Covid6", data=dataTown).fit()

In [66]:
print(est1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.778
Model:                            OLS   Adj. R-squared:                  0.778
Method:                 Least Squares   F-statistic:                     9205.
Date:                Sun, 01 May 2022   Prob (F-statistic):               0.00
Time:                        20:19:53   Log-Likelihood:            -6.6472e+05
No. Observations:               52641   AIC:                         1.329e+06
Df Residuals:                   52620   BIC:                         1.330e+06
Df Model:                          20
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                      -2.39e+05   1.26e+04    -18.961      0.000   -2.64e+05   -2.14e+05
flat_type[T.2 ]               -1.086e+04   1.47e+04     -0.738      0.460   -3.97e+04     1.8e+04
flat_type[T.3 ]                2.523e+04   1.46e+04      1.728      0.084   -3391.105    5.39e+04
flat_type[T.4 ]                3.597e+04   1.48e+04      2.426      0.015    6904.041     6.5e+04
flat_type[T.5 ]                5.208e+04   1.51e+04      3.451      0.001    2.25e+04    8.17e+04
flat_type[T.EXECUTIVE]         9.326e+04   1.55e+04      6.019      0.000    6.29e+04    1.24e+05
flat_type[T.MULTI GENERATION]  2.033e+05   2.12e+04      9.582      0.000    1.62e+05    2.45e+05
storey                         5675.2631     59.740     95.000      0.000    5558.172    5792.354
area_sqm                       3745.3341     46.676     80.242      0.000    3653.849    3836.819
lease_rem                      4091.7629     29.150    140.370      0.000    4034.629    4148.897
d1                             1.069e+05   3181.763     33.598      0.000    1.01e+05    1.13e+05
d2                             2.725e+04   2337.261     11.661      0.000    2.27e+04    3.18e+04
d3                             4.092e+04   2741.062     14.928      0.000    3.55e+04    4.63e+04
d4                            -9.847e+04   2321.631    -42.415      0.000   -1.03e+05   -9.39e+04
d5                             -1.59e+05   2329.272    -68.246      0.000   -1.64e+05   -1.54e+05
d6                            -1.566e+05   2488.379    -62.948      0.000   -1.62e+05   -1.52e+05
Covid                          1.459e+04    779.897     18.709      0.000    1.31e+04    1.61e+04
Covid1                        -4512.1885   3233.317     -1.396      0.163   -1.08e+04    1825.143
Covid2                         6225.0868   1503.132      4.141      0.000    3278.934    9171.240
Covid3                        -8059.0846   2430.830     -3.315      0.001   -1.28e+04   -3294.637
Covid4                         1212.3386   1207.483      1.004      0.315   -1154.339    3579.016
Covid5                         1.123e+04   1333.188      8.424      0.000    8618.149    1.38e+04
Covid6                         8494.0096   1754.914      4.840      0.000    5054.362    1.19e+04
==============================================================================
Omnibus:                     5074.418   Durbin-Watson:                   0.745
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7868.637
Skew:                           0.725   Prob(JB):                         0.00
Kurtosis:                       4.219   Cond. No.                     3.48e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.82e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [69]:
est2 = smf.ols(formula="Y ~ flat_type + storey + area_sqm + lease_rem + d1 + d2 + d3 + d4 + d5 + d6 + Covid", data=dataTown).fit()

In [70]:
print (est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.777
Model:                            OLS   Adj. R-squared:                  0.777
Method:                 Least Squares   F-statistic:                 1.225e+04
Date:                Sun, 01 May 2022   Prob (F-statistic):               0.00
Time:                        20:25:29   Log-Likelihood:            -6.6475e+05
No. Observations:               52641   AIC:                         1.330e+06
Df Residuals:                   52625   BIC:                         1.330e+06
Df Model:                          15
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                     -2.401e+05   1.26e+04    -19.039      0.000   -2.65e+05   -2.15e+05
flat_type[T.2 ]               -1.088e+04   1.47e+04     -0.739      0.460   -3.97e+04     1.8e+04
flat_type[T.3 ]                2.523e+04   1.46e+04      1.727      0.084   -3405.951    5.39e+04
flat_type[T.4 ]                3.599e+04   1.48e+04      2.426      0.015    6909.493    6.51e+04
flat_type[T.5 ]                5.214e+04   1.51e+04      3.453      0.001    2.25e+04    8.17e+04
flat_type[T.EXECUTIVE]         9.338e+04   1.55e+04      6.024      0.000     6.3e+04    1.24e+05
flat_type[T.MULTI GENERATION]  2.038e+05   2.12e+04      9.600      0.000    1.62e+05    2.45e+05
storey                         5678.0980     59.748     95.033      0.000    5560.990    5795.205
area_sqm                       3744.5582     46.697     80.188      0.000    3653.032    3836.085
lease_rem                      4089.3603     29.138    140.343      0.000    4032.249    4146.472
d1                              1.03e+05   2652.495     38.841      0.000    9.78e+04    1.08e+05
d2                             2.922e+04   2190.700     13.339      0.000    2.49e+04    3.35e+04
d3                              3.52e+04   2413.596     14.584      0.000    3.05e+04    3.99e+04
d4                            -9.938e+04   2222.540    -44.712      0.000   -1.04e+05    -9.5e+04
d5                            -1.547e+05   2231.764    -69.302      0.000   -1.59e+05    -1.5e+05
d6                            -1.535e+05   2313.560    -66.334      0.000   -1.58e+05   -1.49e+05
Covid                          1.947e+04    648.775     30.014      0.000    1.82e+04    2.07e+04
==============================================================================
Omnibus:                     5044.267   Durbin-Watson:                   0.745
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7807.151
Skew:                           0.722   Prob(JB):                         0.00
Kurtosis:                       4.213   Cond. No.                     3.53e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.63e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.